# Generated by Django 4.1.7 on 2024-04-19 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentTable',
            fields=[
                ('ParentName', models.CharField(max_length=500)),
                ('DriverName', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('ParentEmail', models.EmailField(max_length=254)),
                ('Password', models.TextField()),
                ('ConfirmPassword', models.TextField()),
            ],
            options={
                'db_table': 'ParentTable',
            },
        ),
        migrations.CreateModel(
            name='SpeedDriver',
            fields=[
                ('Speed_ID', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('target_speed', models.FloatField()),
                ('Drivername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speed_drivers', to='dashboard.parenttable')),
            ],
            options={
                'db_table': 'SpeedDriver',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('Results_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DrivingDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('target_speed', models.FloatField()),
                ('Max_speed', models.FloatField()),
                ('Route', models.TextField()),
                ('Overspeed', models.BooleanField()),
                ('Count_overspeed', models.IntegerField()),
                ('Driver_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Results_drivers', to='dashboard.parenttable')),
            ],
            options={
                'db_table': 'Results',
            },
        ),
        migrations.CreateModel(
            name='ParentDashboard',
            fields=[
                ('ParentDashboard_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DriveDate', models.DateTimeField(default=datetime.datetime.now)),
                ('StartAddress', models.TextField()),
                ('EndAddress', models.TextField()),
                ('Countofoverspeed', models.IntegerField()),
                ('Driver_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dashboard_drivers', to='dashboard.parenttable')),
            ],
            options={
                'db_table': 'ParentDashboard',
            },
        ),
    ]
